Reformat code with black
BinaryAnalysisPlatform/bap-python pull request #13
Opened 2020-06-03 07:36 UTC by XVilka

[Black](https://github.com/psf/black) is the uncompromising Python code formatter. By using it, you agree to cede control over minutiae of hand-formatting. In return, Black gives you speed, determinism, and freedom from pycodestyle nagging about formatting. You will save time and mental energy for more important matters.

Blackened code looks the same regardless of the project you're reading. Formatting becomes transparent after a while and you can focus on the content instead.

Black makes code review faster by producing the smallest diffs possible.

2020-09-21 07:12 UTC, XVilka commented
Updated, also fixed some of the Codacy issues. @ivg @gitoleg please take a look.

2020-09-21 13:25 UTC, ivg commented on src/bap/arm.py
> +
This renders the module totally unreadable. The whole idea is that you can quickly see different variants of the ADT.

2020-09-21 13:27 UTC, ivg commented on src/bap/rpc.py
> +                if "error" in self.msg:
it looks like that there was a bug here

2020-09-21 13:29 UTC, ivg requested changes
I am definitely against the black formatting, it destroys code readability. There is, however, a real bug fix (the second commit) which we will happily accept. 

Thanks!

2020-09-22 06:53 UTC, XVilka commented
Closing in favor or just fixes then: https://github.com/BinaryAnalysisPlatform/bap-python/pull/15

2020-09-22 06:53 UTC, closed without merging